version: '3.8'

services:
  strapi:
    container_name: strapi-boccgk0
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_CLIENT: '${DATABASE_CLIENT}'
      DATABASE_HOST: strapiDB
      DATABASE_PORT: '${DATABASE_PORT}'
      DATABASE_NAME: '${DATABASE_NAME}'
      DATABASE_USERNAME: '${DATABASE_USERNAME}'
      DATABASE_PASSWORD: '${DATABASE_PASSWORD}'
      JWT_SECRET: '${JWT_SECRET}'
      ADMIN_JWT_SECRET: '${ADMIN_JWT_SECRET}'
      APP_KEYS: '${APP_KEYS}'
      NODE_ENV: '${NODE_ENV}'
    volumes:
      - './config:/opt/app/config'
      - './src:/opt/app/src'
      - './package.json:/opt/package.json'
      - './yarn.lock:/opt/yarn.lock'
      - './.env:/opt/app/.env'
      - './public/uploads:/opt/app/public/uploads'
    ports:
      - '1337:1337'
    networks:
      - strapi
      - boccgk0
    depends_on:
      - strapiDB
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.282
      - coolify.serviceId=36
      - coolify.type=service
      - coolify.name=strapi-boccgk0
      - coolify.pullRequestId=0
      - coolify.service.subId=50
      - coolify.service.subType=application
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.http-0-boccgk0-strapi.entryPoints=http
      - traefik.http.routers.http-0-boccgk0-strapi.middlewares=redirect-to-https
      - 'traefik.http.routers.http-0-boccgk0-strapi.rule=Host(`str.mgrec.eu`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-boccgk0-strapi.entryPoints=https
      - traefik.http.routers.https-0-boccgk0-strapi.middlewares=gzip
      - 'traefik.http.routers.https-0-boccgk0-strapi.rule=Host(`str.mgrec.eu`) && PathPrefix(`/`)'
      - traefik.http.routers.https-0-boccgk0-strapi.tls.certresolver=letsencrypt
      - traefik.http.routers.https-0-boccgk0-strapi.tls=true
      - 'caddy_0.encode=zstd gzip'
      - 'caddy_0.handle_path.0_reverse_proxy={{upstreams}}'
      - 'caddy_0.handle_path=/*'
      - caddy_0.header=-Server
      - 'caddy_0.try_files={path} /index.html /index.php'
      - 'caddy_0=https://str.mgrec.eu'
      - caddy_ingress_network=boccgk0

  strapiDB:
    container_name: strapiDB-boccgk0
    platform: linux/amd64
    restart: unless-stopped
    image: 'mysql:5.7'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_USER: '${DATABASE_USERNAME}'
      MYSQL_ROOT_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_PASSWORD: '${DATABASE_PASSWORD}'
      MYSQL_DATABASE: '${DATABASE_NAME}'
    volumes:
      - 'boccgk0_strapi-data:/var/lib/mysql'
    ports:
      - '3306:3306'
    networks:
      - strapi
      - boccgk0
    labels:
      - coolify.managed=true
      - coolify.version=4.0.0-beta.282
      - coolify.serviceId=36
      - coolify.type=service
      - coolify.name=strapiDB-boccgk0
      - coolify.pullRequestId=0
      - coolify.service.subId=28
      - coolify.service.subType=database

volumes:
  strapi-data: null
  boccgk0_strapi-data:
    name: boccgk0_strapi-data

networks:
  strapi: null
  boccgk0:
    name: boccgk0
    external: true
